version: '3.8'

services:
  laravel:
    build: ./laravel_app
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./laravel_app:/var/www/html
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mongo

  react:
    build: ./react_app
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./react_app:/app
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
