version: '3.8'

services:
  nest:
    build: ./nest_app
    container_name: nest_app
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nest_db
    depends_on:
      - mongo

  react:
    build: ./react_app
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
